{% set name = "timemory" %}
{% set version = "3.2.2.dev0" %}

{% set generator = "NMake Makefiles" %}  # [win]
{% set generator = "Unix Makefiles" %}  # [not win]

{% set cmake_args = "" %}

{% set generator_args = "-j2" %}  # [not win]
{% set generator_args = "" %}  # [win]

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0b804db14563acdbf0d42ab033b94547831648278fdd557c68e79172c91ab6db

build:
  number: 1
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt \
    -G \"{{ generator }}\" \
    --cxx-standard=17 \
    --enable-portable \
    --enable-static-libs \
    --disable-c \
    --disable-cuda \
    --disable-fortran \
    --disable-ert \
    --disable-develop \
    --disable-shared-libs \
    --disable-unity-build \
    --disable-require-packages \
    --disable-ompt \
    --disable-upcxx \
    --disable-kokkos \
    --disable-caliper \
    --disable-dyninst \
    --disable-gperftools \
    --disable-compiler-instrumentation \
    --disable-install-rpath-use-link-path \
    --skip-generator-test \
    -- {{ cmake_args }} \
    -- {{ generator_args }}"
  skip: true  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - python
    - pip
    - cython
    - pybind11
    - pybind11-abi
    - scikit-build
    - {{ mpi }}  # [linux and mpi != 'nompi']
  run:
    - python
    - six
    - numpy
    - pydot
    - pillow
    - pandas
    - matplotlib-base
    - multiprocess
    - mpi4py  # [linux and mpi != 'nompi']
    - {{ mpi }}  # [linux and mpi != 'nompi']

test:
  imports:
    - timemory
    - timemory.settings
    - timemory.profiler
    - timemory.trace
    - timemory.util

about:
  home: https://github.com/NERSC/timemory.git
  license: MIT
  license_family: MIT
  license_file: 'LICENSE'
  summary: 'Lightweight performance analysis toolkit and suite of tools'
  description: |
    Lightweight, cross-language utility for recording timing, memory, resource usage, and hardware counters on the CPU and GPU.
    Timemory provides 40+ metrics for C, C++, CUDA, and/or Python codes that can arbitrarily composed into distinct toolsets
    which can inter-weaved and without nesting restrictions.
  doc_url: 'https://timemory.readthedocs.io/'
  dev_url: 'https://github.com/NERSC/timemory.git'

extra:
  recipe-maintainers:
    - jrmadsen
